// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4ER15Ypc7TCAXGlt_1tvmXEuLpXal14k',
    appId: '1:558548226148:web:01051d9600a5174e9ecf71',
    messagingSenderId: '558548226148',
    projectId: 'safewalkscu',
    authDomain: 'safewalkscu.firebaseapp.com',
    databaseURL: 'https://safewalkscu-default-rtdb.firebaseio.com',
    storageBucket: 'safewalkscu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq2OPHqvyuwD-XJyqyjeMBifApu-U30ec',
    appId: '1:558548226148:android:cadf3892611285f19ecf71',
    messagingSenderId: '558548226148',
    projectId: 'safewalkscu',
    databaseURL: 'https://safewalkscu-default-rtdb.firebaseio.com',
    storageBucket: 'safewalkscu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4c9OPWUMdeb_FnuH-dVwDhElnnkQ90LQ',
    appId: '1:558548226148:ios:4ed85379a7ba4da39ecf71',
    messagingSenderId: '558548226148',
    projectId: 'safewalkscu',
    databaseURL: 'https://safewalkscu-default-rtdb.firebaseio.com',
    storageBucket: 'safewalkscu.appspot.com',
    iosClientId: '558548226148-fu7tf0lkv4a9g6kn26ad1b0tplqhkdoq.apps.googleusercontent.com',
    iosBundleId: 'com.example.safewalkAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4c9OPWUMdeb_FnuH-dVwDhElnnkQ90LQ',
    appId: '1:558548226148:ios:f1cf0bf267404ccc9ecf71',
    messagingSenderId: '558548226148',
    projectId: 'safewalkscu',
    databaseURL: 'https://safewalkscu-default-rtdb.firebaseio.com',
    storageBucket: 'safewalkscu.appspot.com',
    iosClientId: '558548226148-5730go7ritv1cu6onfao12bahs8ljerk.apps.googleusercontent.com',
    iosBundleId: 'com.example.safewalkAdmin.RunnerTests',
  );
}
